/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'HarryPaek' at '16. 12. 10 오후 7:27' with Gradle 3.2.1
 *
 * @author HarryPaek, @date 16. 12. 10 오후 7:27
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
